[package]
name = "bpl-hasura"
version = "0.1.0"
edition = "2021"

[dependencies]
anchor-spl = "0.24.2"
bs58 = "0.4.0"
clap = { version="3.1.18", features=["derive"] }
deadpool-postgres= "0.10.2"
dotenv = "0.15.0"
futures = "0.3.21"
log = "0.4.17"
bpl-token-metadata = { path = "../token-metadata/program"}
mpl-auction-house = { version = "1.1.6", features = ["no-entrypoint"] }
gql_client = "1.0.4"
mpl-token-metadata = "1.2.7"
tokio-postgres = "0.7.6"
reqwest = { version = "0.11.10",  features = ["json"] }
serde = {version= "1.0.137", features = ["derive"]}
serde_json = "1.0.81"
solana-sdk = "1.9.15"
spl-token = "3.2.0"
tokio = { version = "1.18.2", features = ["full"] }
tracing = "0.1.35"
tracing-subscriber = "0.3.11"
url = "2.2.2"